[project]
name = "risk-free-portfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipython>=8.18.1",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "numpy-financial>=1.0.0",
    "pandas>=2.3.3",
]
